name: Convert to PDF and Manage Storage

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  convert-and-manage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install SQLite
        run: sudo apt-get install -y sqlite3

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Install Python dependencies
        run: |
          pip install requests flask werkzeug

      - name: Run batch conversion and repo management
        run: python3 app.py batch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
